### ISSUE TITLE
malformed parameter "url"

### ISSUE THREAD

**Issue by macidev** [shopware/production#30] opened 2020-04-07 08:08 UTC
Hi, 
during installation via 

`bin/console system:setup`

and entering "127.0.0.1" for database and "http://somefancyurl.tld/subfolder" i got the error 

> malformed parameter "url"

Runnin the web based installer via browser results in perfect running shop (after building admin and storefront). 

I got this twice on different servers and different urls.

**Comment by shyim** [comment] 2021-05-21 08:27
I could not reproduce it anymore on the newest version.

**Comment by imagine6** [comment] 2021-11-05 08:17
This happens when the Database password includes a question mark -> ?

**Comment by fxp** [comment] 2021-11-18 05:09
> This happens when the Database password includes a question mark -> ?

Yes, I can re create the bug as well

**Comment by christoph-kluge** [comment] 2021-11-26 13:32
I can confirm this bug on v6.4.6.1 with a password containing `#`

**Comment by weselben** [comment] 2021-11-30 10:08
Yea i can confirm and reproduce both, still not fixed in Shopware v6-4-6-1

**Comment by keulinho** [comment] 2021-11-30 10:32
Do you set the database-url with the `--database-url` option or do you configure the database connection through the interactive mode?

**Comment by christoph-kluge** [comment] 2021-11-30 10:35
> Do you set the database-url with the `--database-url` option or do you configure the database connection through the interactive mode?

In my case it was through the interactive web interface.

**Comment by keulinho** [comment] 2021-11-30 11:00
I can confirm that the UI installer currently has problems with `?` or `#` in the DB password.

I created a [ticket](https://issues.shopware.com/issues/NEXT-19088) for that and hopefully we can provide a fix shortly.

**Closed** 2021-12-06 15:12 UTC
