### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by erik-seifert** [shopware/production#8] opened 2020-02-10 10:52 UTC
Get always this error on installation (following readme)

```
PHP Fatal error:  Uncaught OutOfBoundsException: Required package "shopware/platform" is not installed: cannot detect its version in /home/erik/projects/ks/shopware/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php:44
```

**Comment by shyim** [comment] 2020-02-18 12:10
I could not reproduce that issue. Have you a plugin installed which also uses PackageVersions?

**Comment by shopworksnl** [comment] 2020-02-18 21:36
@b-connect  change APP_ENV=dev to APP_ENV=prod inside .env fixes it for me.

**Comment by shyim** [comment] 2020-02-19 07:47
Hey @shopworksnl,

still, cannot reproduce it. :cry: 

I did clone 6.1 branch.
* composer install
* ./bin/console system:setup (choosed dev)
* ./bin/console system:install --create-database --basic-setup

**Comment by wrongspot** [comment] 2020-03-11 12:17
@b-connect  i had this issue by trying to set up a gitlab pipeline and this kind of error appears, when i tried run composer install with --no-scripts option.  Package "ocramius/package-versions" needs to have script activated during install, otherwhise [Versions.php](https://github.com/Ocramius/PackageVersions/blob/master/src/PackageVersions/Versions.php ) can not created via [POST_AUTOLOAD_DUMP Event](https://github.com/Ocramius/PackageVersions/blob/master/src/PackageVersions/Installer.php#L95).

**Comment by MDSLKTR** [comment] 2020-07-01 17:03
When using the 6.1 tag, this works as expected. I get this error on a fresh pull of 6.2 or 6.2.2 as described above @shyim

**Comment by MDSLKTR** [comment] 2020-07-02 08:09
this can be resolved by deleting `vendor/autoload.php` if you ran composer install without scripts before

**Comment by CSalih** [comment] 2020-08-10 15:50
I get this error, when i run composer install on a Gitlab pipeline with a cached vendor folder. The only to avoid this is is to remove the vendor folder and run `composer install`. But this causes a huge build time.
Version 6.3

**Comment by vanWittlaer** [comment] 2020-11-08 10:12
As the stub in Version.php says, this happens when running composer install/update w/ `--no-scripts`. The point is, in 6.2/6.3 composer.json in the post-install-cmd the script `bin/console system:update:finish` is triggered **if** the file install.lock exists.

Now, when I run composer install during build on a gitlab runner (for deploying custom production systems, that do have a install.lock file), then of course `system:update:finish` fails as it has no access to the database. So what to do? Run composer w/ `--no-scripts`? Not a good idea - see above. 

As a workaround, I ended up removing install.lock from the runner while executing composer install, and then add it back later  and run assets:install on the target server. Not sure whether this is a proper solution.

I wonder whether one should perhaps avoid requiring database access from within a composer.json at all?

**Comment by soebbing** [comment] 2020-11-09 08:29
@vanWittlaer You can run `composer install --no-scripts && composer dump-autoload -o`, after which the shop is in a working state again

**Comment by vanWittlaer** [comment] 2020-11-11 11:22
Thx @soebbing but I do want to run the post-install-cmds, just not the system:update:finish step whilst building on a runner.

**Comment by wrongspot** [comment] 2020-11-17 08:53
@vanWittlaer why would you do that on pipeline? post-install-command will trigger database migration. but your production database is not on gitlab. as @soebbing says, run `composer install --no-scripts && composer dump-autoload -o` on your pipline and than deploy this artefakt to production server. On production server you have to call the migration command. via `bin/console system:update:finish`.

**Comment by vanWittlaer** [comment] 2020-11-17 12:02
@wrongspot Thx very much for taking the time to reply. I have read (and believe understood) @soebbing 's correct reply - no need to repeat it.

To answer your question, in my build step, I simply wouldn't want to miss the first two steps of the post-install-cmd
```
        "post-install-cmd": [
            "@composer install --working-dir vendor/shopware/recovery --no-interaction --no-scripts",
            "@composer install --working-dir=vendor/shopware/recovery/Common --no-interaction --optimize-autoloader --no-suggest",
            "[ ! -f install.lock ] || bin/console system:update:finish"
        ],
```
Adding those steps to my pipeline and running --no-scripts would mean I'd miss any further changes in the composer.json, right? Perhaps one could make the execution of update:finish dependent on the existence of the DATABASE_URL env variable instead of on file existence of install.lock?

**Comment by wrongspot** [comment] 2020-11-17 12:32
The question is, why you need Recovery on Production Server? When Database is lost, you clearly have another big problem and you don't want every customer to be able to fill out the recovery form. commit install.lock in your repo and everything is fine.
 
If you really need that in your artifact, you can also integrate the top 2 composer scripts via build scripts in .gitlab-ci.yml. When you transfer build artifact to production, everything is there.

**Comment by vanWittlaer** [comment] 2020-11-17 12:57
Why would I need recovery on production server? Do I, don't I? Sorry, I lost you - drawing a line here. Thx again for your help.

**Comment by shyim** [comment] 2021-03-02 08:23
In meanwhile We have removed PackageVersions as it makes problems. This works now from the generated InstalledVersions from composer 2

**Closed by shyim** 2021-03-02 08:23 UTC
Labels: Incomplete

**Comment by pogster** [comment] 2021-04-09 12:57
For any Google users coming here like me:
We only just started using --no-scripts in gitlab-ci context, and it gave me 'Package "shopware/platform" is not installed' (6.3.5.2).

What worked for me is @vanWittlaer's workaround:

> As a workaround, I ended up removing install.lock from the runner while executing composer install, and then add it back later and run assets:install on the target server. Not sure whether this is a proper solution.

And I totally agree with this. Composer should not do anything with db access.
> I wonder whether one should perhaps avoid requiring database access from within a composer.json at all?
