### ISSUE TITLE
Upgrade from 6.3.0.2 to 6.3.1.0

### ISSUE THREAD

**Issue by barbanet** [shopware/production#65] opened 2020-09-10 06:36 UTC
In the past I used composer to upgred minor versions. For example, from 6.3.0.1 to 6.3.0.2.

I did it by executing this command:

`composer update shopware/*`

At the end I got this error:

```
all migrations executed
cleared the shopware cache
05:42:22 ERROR     [console] Error thrown while running command "system:update:finish". Message: "Too few arguments to function Shopware\Storefront\Theme\StorefrontPluginConfiguration\StorefrontPluginConfigurationFactory::__construct(), 0 passed in /var/www/html/var/cache/prod_h5ee38337f46d70fb9e60ac69262f8b3e/ContainerON2CpeB/srcShopware_Production_KernelProdContainer.php on line 7276 and exactly 1 expected" ["exception" => ArgumentCountError { …},"command" => "system:update:finish","message" => "Too few arguments to function Shopware\Storefront\Theme\StorefrontPluginConfiguration\StorefrontPluginConfigurationFactory::__construct(), 0 passed in /var/www/html/var/cache/prod_h5ee38337f46d70fb9e60ac69262f8b3e/ContainerON2CpeB/srcShopware_Production_KernelProdContainer.php on line 7276 and exactly 1 expected"]

In StorefrontPluginConfigurationFactory.php line 19:
                                                                               
  Too few arguments to function Shopware\Storefront\Theme\StorefrontPluginCon  
  figuration\StorefrontPluginConfigurationFactory::__construct(), 0 passed in  
   /var/www/html/var/cache/prod_h5ee38337f46d70fb9e60ac69262f8b3e/ContainerON  
  2CpeB/srcShopware_Production_KernelProdContainer.php on line 7276 and exact  
  ly 1 expected
```

I tried to upgrade using the backend and has worked as expected.
Am I doing something wrong with Composer?
Is Composer a valid method to keep the platform up-to-date?
I'll appreciate some directions.

**Comment by shyim** [comment] 2020-09-10 07:12
Hey @barbanet,

thanks for reporting.

Yes of course it is a valid method to update Shopware. Can you give us some context?

* Happens it also without Plugins
* Your Upgrade flow from which version to which version.

I tested locally with:
- Installing 6.2.0.2
- Updating to 6.3.1.0

**Comment by barbanet** [comment] 2020-09-10 14:20
Hi @shyim,

The only plugin I have is the Spanish language package (in one case) and I have a second project with the default installation (installed using Composer too).
I'm running PHP 7.4.
That is happening with a clean install.
The upgrade that I tried was from 6.3.0.2 to 6.3.1.0 and I wasn't able to fix it.

**Comment by shyim** [comment] 2021-05-21 08:24
The issue is already pretty old and we have built a completely new Language plugin. So I close it for now

**Closed as completed by shyim** 2021-05-21 08:24 UTC
Labels: Question
